### ISSUE TITLE
Release doesn't seem to be valid

### ISSUE THREAD

**Issue by ragaskar** [watsonbox/xbmc-confreaks#1]
XBMC claims the release zipfile doesn't have the correct structure -- when I unarchive it, it creates a cpgz file, that, when unarchived, produces the original zip. 

Downloaded the entire repo as a zip, and this installs correctly and permits you to list categories, but doesn't seem to retrieve available videos. 

Thanks for writing this! Will be stoked to get it working; will probably fork and take a crack at a fix (I imagine they changed formats since your last commit), but if you have any advice I'd love to hear it.

**Comment by ragaskar** [comment]
Ahhhh. I guess I see what's happening. This plugin is designed to work with videos with downloadable links; none of which the more recent conferences seem to support (as they've all been pushed to youtube). bummer.

**Comment by watsonbox** [comment]
Hi - apologies for not coming back to you sooner.  Somehow I managed to completely miss this issue.

I've now added support for YouTube and Vimeo videos to the plugin, and packaged it up as v0.2, which should hopefully now be working correctly.  I tested YouTube videos on the [PuppetConf](http://www.confreaks.com/events/puppetconf2012) event, and Vimeo videos on the [ArrrrCamp](http://www.confreaks.com/events/arrrrcamp2012) event.

Thanks for the feedback - glad to hear people are using this!

**Comment by ragaskar** [comment]
Oh sweet! I've been meaning to attempt a fix and send a pull request, but happy I can just pull an update. I'll have an opportunity to test it out early next week.

**Comment by watsonbox** [comment]
Great - let me know if it works okay and I'll close this issue.

**Comment by ragaskar** [comment]
Confreaks seems to have backfilled mp4 files for most of the presentations, so I unfortunately can't find an example that will test the new youtube/vimeo integration.

I still can't install the release directly from a releases/ zipfile, I have to dl the entire repo and then ask XBMC to install that. I haven't done a lot of looking into why that might be, but if I get a chance, I'll try to update.

**Comment by watsonbox** [comment]
Thanks for having a play with this.  That's odd I still can't see any mp4s for the two events I mention in my comment above.

As for the zip, it actually _was_ a zip file exported directly from Github.  I'll see if I can get to the bottom of it.

**Comment by ragaskar** [comment]
Sorry, did not read closely enough. You're right, both ArrrrCamp (vimeo) and PuppetConf (youtube) seem to be working now. Thanks so much, I've really been enjoying watching these from my couch instead of hunched over my laptop. 

Another thing worth noting, I'm not sure I was able to do a 'clean' install of the Confreaks plugin on my XBMC, but it looks like the version didn't bump (that said, pretty sure I'm on latest since youtube/vimeo works).
