### ISSUE TITLE
pending update to confreaks.com website

### ISSUE THREAD

**Issue by CobyR** [watsonbox/xbmc-confreaks#3]
Howard,

Not sure the best way to contact you but I had some questions about how you test this add-on.  I believe I can create a zip file and install locally into XBMC?

I'm going to revamp the confreaks.com web-site and want to make sure that xbmc-confreaks works with the new site.  I've forked the project and will put together a pull request.

Thanks,
-Coby
Founder, Confreaks, LLC

**Comment by watsonbox** [comment]
Hi - sorry somehow I missed this.  Yes that sounds great.  In fact, if you'd like me to make the changes against a test version of the new site I've probably got some time.

You can now install the addon directly from within XBMC - I submitted it to the official addon repo.  Failing that, you should be able to install it with a zip of the repo.

**Comment by watsonbox** [comment]
Thinking about it, the small test suite runs against the live website too, so you could always trigger Travis builds as a quick sanity check...
